version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_yufinder
    restart: always
    environment:
      POSTGRES_DB: db_yufinder
      POSTGRES_USER: yufinder
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
